### PR TITLE
Chef 12.1.2

### PR DESCRIPTION
**Pull request by jdmundrawala**
Not ready yet

### CODE REVIEW

**Comment by billotosyr** [comment]
Hi. Chef client 12.1.2 is available on the download site, but on github, 12.1.2 isn't tagged yet (12.1.1 is). I'm hoping to build 12.1.2 on the IBM Z platform. Will this branch be source of a 12.1.2 tag/release? Is this what I should be building? Thanks... Bill

**Comment by jdmundrawala** [comment]
https://github.com/chef/chef/releases/tag/12.1.2

**Comment by jdmundrawala** [comment]
I guess you might have been talking about omnibus-chef since you posted on the omnibus-chef issue

**Comment by jdmundrawala** [comment]
tagged

**Comment by billotosyr** [comment]
Thanks!

**Pull request merged**
