### PR TITLE
Jmcd/update icon

### PR DESCRIPTION
**Pull request by hamburglar**

### CODE REVIEW

**Comment by sersut** [comment]
Looks sane to me.

**Comment by danielsdeleo** [comment]
I wonder why the old one was so large, if it has to do with retina displays and scaling or if it was just really big for no reason. We should probably run a test build to check that out. :+1: though

**Comment by lamont-granquist** [comment]
LGTM

**Comment by ksubrama** [comment]
Migrated:
https://github.com/chef/chef/pull/4383
https://github.com/chef/chef-dk/pull/639

**Pull request closed without merging**
