### PR TITLE
Update fauxhai, chefspec, and rubocop in chefdk

### PR DESCRIPTION
**Pull request by tas50**
Pull in the latest releases for testing cookbooks

### CODE REVIEW

**Comment by jaym** [comment]
:+1:

**Comment by tas50** [comment]
@chef/client-core can I get a review on this please?

**Comment by lamont-granquist** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0

:+1:

**Comment by ksubrama** [comment]
:ice_cream:

**Comment by danielsdeleo** [comment]
:+1:

**Pull request merged**
