### PR TITLE
Generate package scripts using templates

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by ksubrama** [comment]
/cc @btm @jym @schisamo @chef/engineering-services 

Not over 40 but I didn't touch anything interesting in the shell script.

**Comment by schisamo** [comment]
Super :-1: on this. I would rather we just duplicate the scripts (which rarely change) rather than introduce a software definition which changes core behavior in Omnibus.

**Comment by curiositycasualty** [comment]
:-1: As well, I'd rather see the script generation put into omnibus proper.

**Comment by scotthain** [comment]
I would love to see the script generation in omnibus itself. That being said, that's a pretty big behavior change...

**Comment by ksubrama** [comment]
I'm ok with duplication for now.  This was just a "quick fix" that I wanted to try out.  I'll take this back until we have better support for it in omnibus itself.

**Pull request closed without merging**
