### PR TITLE
Remove bogus symlinks.

### PR DESCRIPTION
**Pull request by juliandunn**
This will fix https://github.com/chef/chef-dk/issues/578

### CODE REVIEW

**Comment by juliandunn** [comment]
Forgot to tag @chef/engineering-services for review

**Comment by curiositycasualty** [comment]
Nice catch :+1:

**Comment by schisamo** [comment]
oh jeeze. :+1: 

/cc @tyler-ball @jaym @danielsdeleo @lamont-granquist

**Comment by lamont-granquist** [comment]
yes :+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by scotthain** [comment]
:+1:

**Pull request merged**
