### PR TITLE
Updated Omnibus with RPM dist tag fixes

### PR DESCRIPTION
**Pull request by schisamo**
This PR brings in an updated RPM packager which adds a Fedora [Dist Tag](http://fedoraproject.org/wiki/Packaging:DistTag) (.e.g. `.el5`, `.el6`, `.el7` etc.) to the package name and spec's [Release Tag](http://fedoraproject.org/wiki/Packaging:NamingGuidelines#Release_Tag). This ensures the RPMs more closely match the Fedora packaging guidelines which many users and tools depend on.

Successful CI runs:
http://manhattan.ci.chef.co/job/angrychef-trigger-ad_hoc/6/downstreambuildview/
http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/20/downstreambuildview/

/cc @josephrdsmith @adamedx @chef/ociv @chef/client-engineers

### CODE REVIEW

**Comment by lamont-granquist** [comment]
:cake:

**Comment by danielsdeleo** [comment]
:+1: :shipit: 

For my edification, did we prove that omnitruck and artifactory work ok with this now?

**Comment by lamont-granquist** [comment]
The release pipeline preprod stages will catch it when we ship 12.1.0 before we ship a bad artifact, and I don't think so.  Pretty certain omnitruck is cool with it at least.

**Comment by schisamo** [comment]
@danielsdeleo Artifactory and Omnitruck should be happy as older versions of Omnibus named our RPMs in a similar way.

**Pull request merged**
