### PR TITLE
ChefDK integration builds should pull in latest InSpec

### PR DESCRIPTION
**Pull request by schisamo**
After chatting with @arlimus we think this is the best way to let end users consume the many improvements and fixes that are happening in `inspec` and `kitchen-inspec`.

We'll need to update the ChefDK release document @tyler-ball @jkeiser.

/cc @chef/compliance @danielsdeleo @fnichol @chef/engineering-services

### CODE REVIEW

**Comment by tyler-ball** [comment]
:+1:

**Comment by arlimus** [comment]
This looks great from my side :+1:
Thank you @schisamo

**Comment by danielsdeleo** [comment]
:+1:

**Comment by coderanger** [comment]
I would like to add this should again accelerate the need for a public version manifest for each package release so on the user support side we can tell what they were actually using.

**Comment by scotthain** [comment]
:+1:

**Pull request merged**
