### PR TITLE
Remove duplicate angrychef resource files after refactoring install path functionality.

### PR DESCRIPTION
**Pull request by ksubrama**

### CODE REVIEW

**Comment by scotthain** [comment]
This makes me happy

**Comment by jaym** [comment]
This is cool. I'm :+1: once it gets a successful run through the jenkins pipeline

**Comment by schisamo** [comment]
As I mentioned in https://github.com/chef/omnibus-chef/pull/551#issuecomment-161988075 many of these changes are duplicated in https://github.com/chef/omnibus-chef/pull/551 so let's get the over into that PR and close this one out.

**Pull request closed without merging**
