### PR TITLE
Move chef definition into omnibus-software.

### PR DESCRIPTION
**Pull request by tylercloke**
Related to https://github.com/chef/omnibus-software/pull/403

[Passing Chef Build](http://manhattan.ci.chef.co/job/chef-trigger-ad_hoc/41/downstreambuildview/)
[Passing Angrychef Build](http://manhattan.ci.chef.co/job/angrychef-trigger-ad_hoc/21/downstreambuildview/)
[Passing ChefDK Build](http://manhattan.ci.chef.co/job/chefdk-trigger-ad_hoc/51/downstreambuildview/)

Ping @chef/lob @chef/client-core 

Motivation for context https://github.com/chef/opscode-omnibus/pull/751

### CODE REVIEW

**Comment by schisamo** [comment]
@tylercloke :+1: I think it goes without saying but lets be sure to squash all the `DEV:*` commits down before a merge.

**Comment by schisamo** [comment]
Take a look at https://github.com/chef/omnibus-software/pull/403#discussion_r28875631 for concerns with moving `openssl-customization` over to `omnibus-software`.

**Comment by tylercloke** [comment]
Yeah `DEV` means definitely will squash lol. Its too bad I can't ping the client-core team myself.

**Comment by danielsdeleo** [comment]
:+1: modulo squashing and undoing the Gemfile change. Would be good to do a test build of the affected projects to make sure there's no non-obvious bug. Also I would nitpick about making the dependency happen sooner so it's more likely to be cached (in the omnibus git cache). But in this case we're literally just copying a file and adding one line to some other file, so I can't imagine it will matter.

**Pull request merged**
