### PR TITLE
Escape maintainer email address.

### PR DESCRIPTION
**Pull request by yzl**
cc @danielsdeleo @jdmundrawala 

This fixes the broken build of chefdk on windows.

working build:  http://manhattan.ci.chef.co/job/chefdk-build/109/architecture=x86_64,platform=windows-2008r2,project=chefdk,role=builder/console

### CODE REVIEW

**Comment by jdmundrawala** [comment]
:shipit: 
Do we need to make the same changes for the chef client packages?

**Comment by danielsdeleo** [comment]
:shipit:

**Comment by yzl** [comment]
@jdmundrawala For consistency, we should do it for all our packages.  I'm planning to roll it in with other packaging-related work I have slated.  That work for you?

**Comment by jdmundrawala** [comment]
it missed chef client 12.1.0.rc.0, but we should do it for the GA release

**Comment by yzl** [comment]
will do.

**Comment by schisamo** [comment]
@yzl let's make sure that fix makes it into the default template that ships in Omnibus the framework also:
https://github.com/chef/omnibus/blob/master/resources/msi/localization-en-us.wxl.erb#L5

**Comment by yzl** [comment]
@jdmundrawala Done for the chef-client packages: #345 

@schisamo Done for omnibus:    https://github.com/chef/omnibus/pull/435

**Pull request merged**
