### PR TITLE
MSI signing configuration for Chef Client and Chef DK.

### PR DESCRIPTION
**Pull request by sersut**
**Needs to be merged once the certs are in the build slaves.**

Configure code signing for Chef Client and Chef DK msi packages.

/cc: @jaym

### CODE REVIEW

**Comment by coderanger** [comment]
What will this do if someone other than Chef Software tries to make a build?

**Comment by jaym** [comment]
it will fail

**Comment by jaym** [comment]
:+1:

**Comment by coderanger** [comment]
> it will fail. But so should other things like osx

Can we detect that somehow and do something better like warn and produce an unsigned build if the configured keys aren't available?

**Comment by jaym** [comment]
I'm not a fan of autodetect as it will be hard to distinguish between a real and "expected" failure. I think the plan for this is to add a flag to omnibus that lets you skip signing.

**Comment by coderanger** [comment]
How about something like:

```ruby
signing_identity ENV['CHEF_SIGNING_KEY'], machine_store: true if ENV['CHEF_SIGNING_KEY']
```

and then applying the key to the Chef Software build system?

**Comment by jaym** [comment]
that would also work

**Comment by sersut** [comment]
I think the right thing is to introduce a command line options like `--sign` lack of which will ignore the missing keys. Otherwise we will need to do that for each and every sign configuration we are adding to all the projects.

**Comment by coderanger** [comment]
Even with that, I don't think data values specific to Chef Software's build should probably go in here.

**Comment by schisamo** [comment]
We need to apply changes to the **push-jobs-client** and **angrychef** project definitions.

**Comment by sersut** [comment]
@schisamo thanks for the reminder. Done. Test build on its way.

**Comment by sersut** [comment]
@coderanger I have filed https://github.com/chef/omnibus-chef/issues/445 to settle down our conversation about removing the signing related strings out of omnibus repos.

**Pull request merged**
