### PR TITLE
Bump Chef to 12.5.0 and ChefDK 0.9.0

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by thommay** [comment]
:+1:

**Comment by schisamo** [comment]
What about the override versions on the software defs?

**Comment by jkeiser** [comment]
@schisamo I don't think we don't do that anymore, we just build the release and then merge what was built into stable. For example, we haven't been tagging chef-dk version in the chef-dk omnibus, just tagging that SHA when we release the gem (after we ship).

**Comment by danielsdeleo** [comment]
:+1:  if this is the same as we did last time

**Pull request merged**
