### PR TITLE
ChefDK is getting cached in a subdirectory (chef-dk/chefdk)

### PR DESCRIPTION
**Pull request by tyler-ball**
So we need to pull in omnibus changes to respect that, and modify our appbundle call to use the correct new API

This is an attempt to fix our ChefDK master builds in Manhattan

\cc @jaym @schisamo @danielsdeleo

### CODE REVIEW

**Comment by danielsdeleo** [comment]
Seems kinda weird that omnibus is putting the code in a different location but we didn't consider that a breaking change. Also, is there some extra checking we can do to make sure nothing else is relying on that path?

:+1: if the consensus is to just deal with the omnibus change.

**Comment by schisamo** [comment]
We need to just fix Omnibus. Can you please open a PR with your proposed changes @tyler-ball?

**Comment by jaym** [comment]
omnibus also needs to be changed. The appbundle command was relying on everything being in the same folder. The meaning of `appbundle` in that case was go to `Config.source_dir/app_name` and run appbundler. We need to change the appbundle command to take in a software name, which for most cases will produce the same result.

**Comment by tyler-ball** [comment]
Ugh, I had the branch created but forgot to make the PR for it - https://github.com/chef/omnibus/pull/597 is ready for review now

**Comment by mpasternacki** [comment]
:+1: for Chef's telepathic engineers. My chefdk build has bombed yesterday due to this issue, ran a `git pull` and headed over to github to check if it's known only to find that there is a feature branch with a solution pushed _while the build was already running_. Fixed the problem for me, FWIW.

**Pull request merged**
