### PR TITLE
Update knife-spork to latest 1.5.0 release

### PR DESCRIPTION
**Pull request by jonlives**

### CODE REVIEW

**Comment by stevendanna** [comment]
Big :+1: Speed improvements in 1.5 are substantial:

```
sdanna@thrace ~ > time knife exec -E ''
WARNING: No knife configuration file found

real    0m3.158s
user    0m2.781s
sys     0m0.368s
sdanna@thrace ~ > chef gem install knife-spork
Fetching: knife-spork-1.5.0.gem (100%)
Successfully installed knife-spork-1.5.0
1 gem installed
sdanna@thrace ~ > time knife exec -E ''
WARNING: No knife configuration file found

real    0m0.859s
user    0m0.751s
sys     0m0.104s
```

**Comment by jonlives** [comment]
Awesome stuff! Thanks really to @lamont-granquist for fixing the perf issue, hadn't occurred to me how much non-lazily loading Berkshelf was going to slow things down for chef-dk in general

**Comment by lamont-granquist** [comment]
:+1: :smile:

**Comment by jdmundrawala** [comment]
:+1:

**Pull request merged**
