### PR TITLE
[ES-11] Final Mac OS X El Capitan compat fixes

### PR DESCRIPTION
**Pull request by schisamo**
This ports the Mac OS X El Captian compat fixes introduced in #439 and #466 to the remaining projects that ship in this repo:

* AngryChef
* Push Jobs Client

/cc @chef/engineering-services @chef/client-maintainers @manderson26

### CODE REVIEW

**Comment by yzl** [comment]
:+1:

**Comment by danielsdeleo** [comment]
:+1:

**Comment by patrick-wright** [comment]
I see some copy/paste functions.  I would consider sourcing function scripts in the future.
Otherwise :+1:

**Comment by manderson26** [comment]
:+1:  Looks reasonable to me.

**Pull request merged**
