### PR TITLE
Lcg/ruby 2.2.3

### PR DESCRIPTION
**Pull request by lamont-granquist**
Massive GC improvements in 2.2.x
Massive perf improvements in 2.2.x (chef spec tests are 2x faster than 2.1.6)

### CODE REVIEW

**Comment by lamont-granquist** [comment]
@chef/client-core @chef/client-maintainers 2.2.x has been out since December, lets start using it.

**Comment by ranjib** [comment]
:+1:

**Comment by danielsdeleo** [comment]
IIRC Ruby has committed to following SemVer since 2.1 so we should be good here. From the announcement https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/  there is a "Remove deprecated C APIs" entry. As long as everything builds we should be good though.

:+1:

**Comment by lamont-granquist** [comment]
So far I just did one build on my Ubuntu 14.04 workstation and it was fine.

**Comment by lamont-granquist** [comment]
We've also had ruby 2.2 in the chef/chef test matrix for a long time, and i've been using it on my workstation with rvm for chef dev stuff for months.

**Comment by danielsdeleo** [comment]
That's probably fine, I'd expect it to be a binary thing where gems w/ C exts either fail to build or they don't.

**Comment by coderanger** [comment]
The Halite unit tests have also been running on 2.2 (and 2.1, 2.0) forever with no problems.

**Comment by ranjib** [comment]
i am running 2.2 backed chef client for quiet sometime.. at least with 10 community cookbooks. so those works fine for sure.
https://github.com/ranjib/PiChef/releases/download/0.0.1/chef-12.2.1.deb

**Comment by mcquin** [comment]
:rocket:

**Pull request merged**
