### PR TITLE
update rubocop version

### PR DESCRIPTION
**Pull request by miketheman**
Lot of fixes and cops updated.

https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.31.0.md
https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.30.1.md
https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.30.0.md
https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.29.1.md
https://github.com/bbatsov/rubocop/blob/master/relnotes/v0.29.0.md

### CODE REVIEW

**Comment by miketheman** [comment]
@chef/owners anyone?

**Comment by thommay** [comment]
I'm down :+1:

**Comment by danielsdeleo** [comment]
Fine by me

**Comment by tyler-ball** [comment]
:+1:

**Comment by fnichol** [comment]
Wootness

**Pull request merged**
